version: '3.8'

services:
  backend:
    image: lilperekis/nestmate_backend
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      FLASK_DATASOURCE_URL: postgresql://${db_user}:${db_password}@db:5432/${db_name}
      environment:
      FLASK_RUN_HOST: "0.0.0.0"
      FLASK_RUN_PORT: "5000"
    restart: always
  frontend:
    image: lilperekis/nestmate_frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_BACKEND_HOST: backend
      VITE_BACKEND_PORT: 5000
    restart: always
  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_USER: ${db_user}
      POSTGRES_DB: ${db_name}
    ports:
      - "${db_port}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/postgres/initdb:/docker-entrypoint-initdb.d:ro
    restart: always

volumes:
  db-data: